import type { Exhibit, Exhibition, MuseumRoom } from "./types"

/**
 * Централізований контент музею. Це єдине джерело істини для виставки.
 * Додавайте кімнати та експонати сюди — навігація, 3D-сцени, карта та
 * прогрес оновляться автоматично.
 */

export const ROOMS: MuseumRoom[] = [
  {
    id: "lobby",
    index: 0,
    name: "Вестибюль",
    signage: "Вхід",
    description:
      "Поріг Виставки №4271. Збережена людська історія, закарбована у світлі та камені.",
    kind: "lobby",
    lightingTheme: "lobby",
    ambientAudio: "lobby",
    subtitle: "Збережена людська історія",
  },
  {
    id: "origins",
    index: 1,
    name: "Витоки",
    signage: "Зал 01",
    description:
      "Там, де починається історія. Перші артефакти зв'язку — маленькі, звичайні та тихо монументальні.",
    kind: "gallery",
    lightingTheme: "origins",
    ambientAudio: "origins",
    subtitle: "Початок",
  },
  {
    id: "lab",
    index: 2,
    name: "Лабораторія реконструкції пам'яті",
    signage: "Зал 02",
    description:
      "Центр відновлення фрагментів минулого. Тут спогади збираються по частинках із розрізнених даних.",
    kind: "lab",
    lightingTheme: "lab",
    ambientAudio: "lab",
    subtitle: "Відновлення історичних спогадів",
  },
  {
    id: "lost",
    index: 3,
    name: "Втрачені артефакти",
    signage: "Зал 03",
    description:
      "Деякі переживання неможливо зберегти. Ці вітрини зберігають те, що жоден архів не в силах втримати.",
    kind: "lost",
    lightingTheme: "lost",
    ambientAudio: "lost",
    subtitle: "Те, що неможливо вберегти",
  },
  {
    id: "future",
    index: 4,
    name: "Архів майбутнього",
    signage: "Зал 04",
    description:
      "Артефакти, виставлені як історія — проте їхній час ще не настав. Архів пам'ятає наперед.",
    kind: "future",
    lightingTheme: "future",
    ambientAudio: "future",
    subtitle: "Спогади, що ще не сталися",
  },
  {
    id: "observatory",
    index: 5,
    name: "Обсерваторія хронології",
    signage: "Зал 05",
    description:
      "Нескінченне поле можливих спогадів. Кожна точка світла — це майбутнє, яке ще може бути прожито.",
    kind: "observatory",
    lightingTheme: "observatory",
    ambientAudio: "observatory",
    subtitle: "Поле можливих сценаріїв",
  },
  {
    id: "constellation",
    index: 6,
    name: "Зал можливостей",
    signage: "Зал 06",
    description:
      "Сузір'я ненаписаних моментів, з'єднаних шляхами між ними. Доторкніться до зірки, щоб зазирнути у те, що може бути.",
    kind: "constellation",
    lightingTheme: "constellation",
    ambientAudio: "observatory",
    subtitle: "Ненаписане майбутнє",
  },
  {
    id: "final",
    index: 7,
    name: "Одкровення",
    signage: "Фінальний зал",
    description:
      "Порожня біла кімната. Тільки стіна та проєкція, що розкриває справжню суть виставки.",
    kind: "final",
    lightingTheme: "final",
    ambientAudio: "final",
    subtitle: "Історія продовжується",
  },
]

export const EXHIBITS: Exhibit[] = [
  // ── Room 1: Origins ───────────────────────────────────────────────
  {
    id: "o-001",
    roomId: "origins",
    title: "Перше повідомлення",
    artifactCode: "A-001",
    year: "Початок",
    category: "Листування",
    type: "text",
    plaque: "Одне повідомлення, з якого все почалося.",
    description:
      "Знайдено в ранньому архіві комунікацій. Звичайне для будь-якого спостерігача — і все ж, перша нитка історії, що триватиме роками. Відправник ще не знав, що він розпочинає.",
    media: { kind: "image", src: "/exhibits/first-message.png", alt: "Схоже, тоді обговорення правил було дуже важливим." },
    status: "archived",
    position: [-8, 1.6, -7.4],
  },
  {
    id: "o-002",
    roomId: "origins",
    title: "Перша розмова",
    artifactCode: "A-002",
    year: "Початок",
    category: "Листування",
    type: "text",
    plaque: "Години, що пролетіли як хвилини.",
    description:
      "Архів містить підтвердження існування події, але її повний вміст не зберігся. Дослідники вважають, що саме тут було закладено фундамент усієї подальшої історії. Розмова, що затягнулася далеко за північ. Архів зберігає лише її тривалість та тепло, а не слова — деякі речі завжди мали залишатися лише між двома людьми.",
    status: "archived",
    position: [-4, 1.6, -7.4],
  },
  {
    id: "o-003",
    roomId: "origins",
    title: "Добрий котик",
    artifactCode: "A-003",
    year: "Початок",
    category: "Момент",
    type: "photo",
    plaque: "Перший задокументований випадок присвоєння особливого імені.",
    description: "Архівісти вважають цей момент однією з ранніх ознак формування емоційної прив'язаності. Початкове значення фрази втрачено. Її важливість — ні.",
    media: { kind: "image", src: "/exhibits/good-cat.jpg", alt: "Спогад про першу зміну контакту." },
    status: "archived",
    position: [0, 1.6, -7.4],
  },
  {
    id: "o-004",
    roomId: "origins",
    title: "Мем?",
    artifactCode: "A-004",
    year: "Початок",
    category: "Зображення",
    type: "photo",
    plaque: "Мем невстановленого походження",
    description: "Вважається одним із перших випадків спільного почуття гумору. Наукова цінність: сумнівна. Емоційна цінність: надзвичайна.",
    media: { kind: "image", src: "/exhibits/thm.jpg", alt: "." },
    status: "archived",
    position: [4, 1.6, -7.4],
  },
  {
    id: "o-005",
    roomId: "origins",
    title: "З першої спроби влучив?",
    artifactCode: "A-005",
    year: "Початок",
    category: "Зображення",
    type: "photo",
    plaque: "Квіти, що вперше зʼявились від нього.",
    description: "Перший задокументований випадок, коли почуття набули фізичної форми. Збережений як переломний момент раннього періоду експозиції.",
    media: { kind: "image", src: "/exhibits/first-flower.jpg", alt: "." },
    status: "archived",
    position: [8, 1.6, -7.4],
  },

  // ── Room 2: Memory Reconstruction Lab ─────────────────────────────
  {
    id: "l-001",
    roomId: "lab",
    title: "Серце зі шнурків",
    artifactCode: "R-118",
    year: "Відновлено",
    category: "Реконструкція",
    type: "photo",
    plaque: "Реконструкція завершена на 98.3%.",
    description:
      "Значення артефакту довелося відновлювати за непрямими даними, оскільки його цінність не піддається матеріальній оцінці.",
    media: { kind: "image", src: "/exhibits/heart-from-s.jpg", alt: "Фізичний об'єкт успішно збережено." },
    status: "reconstructing",
    position: [-10, 1.8, -6],
  },
  {
    id: "l-002",
    roomId: "lab",
    title: "Аеліса",
    artifactCode: "R-119",
    year: "Відновлено",
    category: "Спільне створення",
    type: "photo",
    plaque: "Цифрове середовище. Перший задокументований випадок спільного створення.",
    description:
      "Архів досі не може визначити, чому суб'єкти надавали цьому об'єкту настільки високу цінність.",
    media: { kind: "image", src: "/exhibits/aelisa.jpg", alt: "." },
    status: "reconstructing",
    position: [-6, 1.8, -6],
  },
  {
    id: "l-003",
    roomId: "lab",
    title: "Щось на звірячому",
    artifactCode: "R-204",
    year: "Відновлено",
    category: "Спільний перегляд",
    type: "text",
    plaque: "Файл мультфільму збережено..",
    description:
      "Емоції під час перегляду — відновлені лише частково.",
    media: { kind: "image", src: "/exhibits/zootopia.jpg", alt: "Відновлений фрагмент спільного перегляду." },
    status: "reconstructing",
    position: [-2, 1.8, -6],
  },
  {
    id: "l-004",
    roomId: "lab",
    title: "Пакт довіри",
    artifactCode: "R-377",
    year: "Відновлено",
    category: "Цифровий документ",
    type: "photo",
    plaque: "Цифрового підпису було достатньо.",
    description:
      "Дослідники вважають його одним із фундаментальних артефактів усієї експозиції. Значно вплинув на стабільність подальшої хронології.",
    media: { kind: "image", src: "/exhibits/trust.jpg", alt: "Цифровий документ успішно збережено" },
    status: "reconstructing",
    position: [2, 2.4, -7.6],
  },
  {
    id: "l-005",
    roomId: "lab",
    title: "Акт капітуляції",
    artifactCode: "R-378",
    year: "Відновлено",
    category: "Закони серця",
    type: "photo",
    plaque: "Юридична сила: незрозуміла. Емоційна сила: катастрофічна.",
    description:
      "Після підписання документа подальший опір було припинено.",
    media: { kind: "image", src: "/exhibits/capitulation.jpg", alt: "Цифровий документ успішно збережено" },
    status: "reconstructing",
    position: [6, 2.4, -7.6],
  },
  {
    id: "l-006",
    roomId: "lab",
    title: "Особистий архів",
    artifactCode: "R-379",
    year: "Відновлено",
    category: "Засекречений фрагмент",
    type: "photo",
    plaque: "Матеріали: змішані, кількість: невизначена, цінність: безцінна.",
    description:
      "Більшість того, що ми цінуємо — звичайне. Лабораторія все одно врятувала його.",
    media: { kind: "image", src: "/exhibits/table-of-sweet.jpg", alt: "Фрагмент особистого архіву успішно збережено" },
    status: "reconstructing",
    position: [10, 2.4, -7.6],
  },
  // ── Room 3: Lost Artifacts ────────────────────────────────────────
  {
    id: "ls-14",
    roomId: "lost",
    title: "Відчуття перед сном",
    artifactCode: "L-14",
    year: "—",
    category: "Відчуття",
    type: "invisible",
    plaque: "Неможливо архівувати.",
    description:
      "Стан тиші і безпеки що існує лише в моменті і зникає без можливості бути записаним або відтвореним системою",
    status: "impossible",
    position: [-10, 1.4, -6.5],
  },
  {
    id: "ls-22",
    roomId: "lost",
    title: "Той самий момент",
    artifactCode: "L-22",
    year: "—",
    category: "Миттєвість",
    type: "invisible",
    plaque: "Запис відсутній.",
    description:
      "Перехід від звичайної симпатії до чогось більшого який не був зафіксований але залишився як наслідок у всій подальшій історії",
    status: "no-recording",
    position: [-7, 1.4, -7],
  },
  {
    id: "ls-31",
    roomId: "lost",
    title: "Перше 'я сумую'",
    artifactCode: "L-31",
    year: "—",
    category: "Відчуття",
    type: "invisible",
    plaque: "Дані втрачені",
    description:
      "Перше усвідомлення відстані між двома людьми яке існувало лише як емоційний сигнал без повного текстового архіву",
    status: "tech-limitation",
    position: [-4, 1.4, -6.5],
  },
  {
    id: "ls-31",
    roomId: "lost",
    title: "Перша ніч тиші",
    artifactCode: "L-31",
    year: "—",
    category: "Відчуття",
    type: "invisible",
    plaque: "Архів пошкоджено",
    description:
      "Період коли відсутність повідомлень стала відчутною присутністю але не залишила прямого цифрового сліду",
    status: "tech-limitation",
    position: [-1, 1.4, -6.5],
  },
  {
    id: "ls-31",
    roomId: "lost",
    title: "Перше примирення",
    artifactCode: "L-31",
    year: "—",
    category: "Відчуття",
    type: "invisible",
    plaque: "Неможливо реконструювати",
    description:
      "Момент відновлення зв'язку після напруги який існує лише як емоційний відбиток без повного контексту події",
    status: "tech-limitation",
    position: [2, 1.4, -6.5],
  },
  {
    id: "ls-31",
    roomId: "lost",
    title: "Перше 'пробач'",
    artifactCode: "L-31",
    year: "—",
    category: "Відчуття",
    type: "invisible",
    plaque: "Частково втрачено",
    description:
      "Слово збережене але інтонація причина і вага моменту повністю відсутні у системі архівації",
    status: "tech-limitation",
    position: [5, 1.4, -6.5],
  },
  {
    id: "ls-31",
    roomId: "lost",
    title: "Момент довіри",
    artifactCode: "L-31",
    year: "—",
    category: "Відчуття",
    type: "invisible",
    plaque: "Матеріальний носій збережено емоційний стан втрачено",
    description:
      "Документ існує як об'єкт але відчуття яке його створило більше не піддається реконструкції",
    status: "tech-limitation",
    position: [7, 1.4, -6.5],
  },
  {
    id: "ls-31",
    roomId: "lost",
    title: "Тиша між розмовами",
    artifactCode: "L-31",
    year: "—",
    category: "Відчуття",
    type: "invisible",
    plaque: "Не підлягає архівації",
    description:
      "Проміжки між повідомленнями які суб'єктивно здавались значущими але не залишили цифрового сліду",
    status: "tech-limitation",
    position: [10, 1.4, -6.5],
  },

  // ── Room 4: Future Archive ────────────────────────────────────────
  {
    id: "f-001",
    roomId: "future",
    title: "Майбутня подорож",
    artifactCode: "F-031",
    year: "2031",
    category: "Експедиція",
    type: "future",
    plaque: "Очікує створення.",
    description:
      "Задокументований сценарій спільної міської прогулянки у вечірньому місті, де майбутнє фіксується як вже знайомий маршрут між двома людьми, які рухаються в одному темпі.",
    media: { kind: "image", src: "/exhibits/first-walk.png", alt: "Спекулятивна майбутня подорож" },
    status: "awaiting-creation",
    position: [-8, 1.7, -7.4],
  },
  {
    id: "f-002",
    roomId: "future",
    title: "Майбутній дім",
    artifactCode: "F-032",
    year: "Невідома дата",
    category: "Місце",
    type: "future",
    plaque: "У процесі.",
    description:
      "Простір, якого ще не існує фізично, але який уже має внутрішню архітектуру, сформовану з уявлень двох людей про спільне життя і стабільність.",
    media: { kind: "image", src: "/exhibits/our-home.png", alt: "Спекулятивний майбутній дім" },
    status: "pending",
    position: [-4, 1.7, -7.4],
  },
  {
    id: "f-003",
    roomId: "future",
    title: "Майбутня пригода",
    artifactCode: "F-034",
    year: "2034",
    category: "Експедиція",
    type: "future",
    plaque: "Прогнозована хронологія.",
    description:
      "Висотний сценарій спільної подорожі, де майбутнє визначається не локацією, а здатністю двох людей рухатись крізь складний простір, не втрачаючи зв'язку між собою.",
    media: { kind: "image", src: "/exhibits/first-expid.png", alt: "Спекулятивна майбутня пригода" },
    status: "predicted",
    position: [0, 1.7, -7.4],
  },
  {
    id: "f-004",
    roomId: "future",
    title: "Майбутній вечір",
    artifactCode: "F-035",
    year: "2034",
    category: "Вечір на пляжі",
    type: "future",
    plaque: "Прогнозована хронологія.",
    description:
      "Висотний сценарій спільного вечору, де емоції визначаються не локацією, а здатністю двох людей бути разом, тихо і спокійно.",
    media: { kind: "image", src: "/exhibits/first-evening.png", alt: "Спекулятивний майбутній вечір" },
    status: "predicted",
    position: [4, 1.7, -7.4],
  },
  {
    id: "f-005",
    roomId: "future",
    title: "Майбутнє святкування",
    artifactCode: "F-036",
    year: "2034",
    category: "Експедиція",
    type: "future",
    plaque: "Прогнозована хронологія.",
    description:
      "Прогнозований артефакт майбутнього. Святкування, яке ще не відбулося, але вже займає своє місце серед найважливіших спогадів. Символ спільного часу, радості та історій, які лише чекають на свій момент.",
    media: { kind: "image", src: "/exhibits/first-celebration.png", alt: "Спекулятивна майбутня пригода" },
    status: "predicted",
    position: [8, 1.7, -7.4],
  },
  // ── Room 5: Timeline Observatory ──────────────────────────────────
  {
    id: "obs-1",
    roomId: "observatory",
    title: "Літній вечір",
    artifactCode: "P-1042",
    year: "Можливо",
    category: "Майбутнє фото",
    type: "future",
    description: "Довгий вечір без жодних планів. Той тип часу, який здається нескінченним і минає занадто швидко.",
    status: "possible",
  },
  {
    id: "obs-2",
    roomId: "observatory",
    title: "Невідома пригода",
    artifactCode: "P-2087",
    year: "Можливо",
    category: "Майбутній спогад",
    type: "future",
    description: "Десь, де ніхто з них не був, роблячи те, чого ніхто не робив. Деталі ще не написані. Компанія незмінна.",
    status: "possible",
  },
  {
    id: "obs-3",
    roomId: "observatory",
    title: "Майбутнє святкування",
    artifactCode: "P-3120",
    year: "Можливо",
    category: "Майбутній спогад",
    type: "future",
    description: "Привід зібратися, підняти тост, згадати пізніше. Подія ще не визначена. Вона обов'язково буде.",
    status: "possible",
  },
  {
    id: "obs-4",
    roomId: "observatory",
    title: "Спільна прогулянка",
    artifactCode: "P-4051",
    year: "Можливо",
    category: "Майбутній спогад",
    type: "future",
    description: "Без мети. Прогулянка і є мета. Це спогади, які ніколи не потрапляють у заголовки, але завжди створюють життя.",
    status: "possible",
  },
  {
    id: "obs-5",
    roomId: "observatory",
    title: "Новий початок",
    artifactCode: "P-5009",
    year: "Можливо",
    category: "Майбутній спогад",
    type: "future",
    description: "Двері, що ще не відчинені. За ними — глава, яку ще ніхто не читав, бо ніхто її ще не прожив.",
    status: "possible",
  },
  {
    id: "obs-6",
    roomId: "observatory",
    title: "Тихий ранок",
    artifactCode: "P-6033",
    year: "Можливо",
    category: "Майбутнє фото",
    type: "future",
    description: "Повільне світло, ще повільніша кава, жодного поспіху. Звичайний ранок, який виявиться одним із найкращих.",
    status: "possible",
  },

  // ── Room 6: Hall of Possibilities ──────────────────────────────────
  {
    id: "con-1",
    roomId: "constellation",
    title: "Ненаписана річниця",
    artifactCode: "X-001",
    year: "2040+",
    category: "Можливість",
    type: "future",
    description: "Віха, яка ще не відбулася. Сузір'я відстежує це як вузол високої ймовірності, залежний від тисяч дрібних рішень, які ще належить прийняти.",
    status: "possible",
  },
  {
    id: "con-2",
    roomId: "constellation",
    title: "Спільна тиша",
    artifactCode: "X-002",
    year: "Майбутнє",
    category: "Можливість",
    type: "future",
    description: "Момент, коли слова більше не потрібні. Глибокий, стабільний зв'язок, який архів передбачає як фундамент їхніх пізніх років.",
    status: "possible",
  },
  {
    id: "con-3",
    roomId: "constellation",
    title: "Невідоме місто",
    artifactCode: "X-003",
    year: "Майбутнє",
    category: "Можливість",
    type: "future",
    description: "Місце, яке вони відвідають разом. Архів не може назвати його, але він розпізнає атмосферу відкриттів та спільну карту між ними.",
    status: "possible",
  },
  {
    id: "con-4",
    roomId: "constellation",
    title: "Спадщина доброти",
    artifactCode: "X-004",
    year: "2050+",
    category: "Можливість",
    type: "future",
    description: "Вплив, який їхні життя матимуть на інших. Точка сузір'я, що світиться яскравіше завдяки кумулятивному теплу їхніх спільних дій.",
    status: "possible",
  },
  {
    id: "con-5",
    roomId: "constellation",
    title: "Останнє перше",
    artifactCode: "X-005",
    year: "Майбутнє",
    category: "Можливість",
    type: "future",
    description: "Самий останній раз, коли вони роблять щось уперше. Архів відзначає це як прекрасний парадокс — життя, яке ніколи не перестає починатися.",
    status: "possible",
  },
  {
    id: "con-6",
    roomId: "constellation",
    title: "Безперервність",
    artifactCode: "X-006",
    year: "Завжди",
    category: "Можливість",
    type: "future",
    description: "Нитка, що з'єднує все. Не окрема подія, а простий, наполегливий акт того, щоб бути поруч. Найскладніший артефакт у всьому музеї.",
    status: "possible",
  },
]

export const EXHIBITION: Exhibition = {
  id: "4271",
  code: "Виставка №4271",
  title: "Юлія та Юрій",
  subtitle: "Збережена людська історія",
  rooms: ROOMS,
}

// ── Selectors ───────────────────────────────────────────────────────

export function getRoom(id: string): MuseumRoom | undefined {
  return ROOMS.find((r) => r.id === id)
}

export function getExhibitsForRoom(roomId: string): Exhibit[] {
  return EXHIBITS.filter((e) => e.roomId === roomId)
}

export function getExhibit(id: string): Exhibit | undefined {
  return EXHIBITS.find((e) => e.id === id)
}

/** Впорядкований список id кімнат для лінійної навігації. */
export const ROOM_ORDER: string[] = [...ROOMS]
  .sort((a, b) => a.index - b.index)
  .map((r) => r.id)
